#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

//IDI ICON
//IDC CLASS
//IDS STRING
#define IDI_MWIND 109
#define IDC_MWIND 110
#define IDS_APP_TITLE 111

#endif // RESOURCE_H_INCLUDED
